version: "3.8"

services:
  functiongemma-270m-vllm:
    image: vllm/vllm-openai:v0.13.0
    container_name: functiongemma-270m-vllm

    runtime: nvidia
    shm_size: "1gb"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - /root/.cache/huggingface:/root/.cache/huggingface

    ports:
      - "8004:8000"

    command: >
      --model google/functiongemma-270m-it
      --served-model-name functiongemma-270m
      --max-model-len 8192
      --gpu-memory-utilization 0.7

    restart: unless-stopped